trial:
  actionBufferLifespan: 1
  actionSpace:
  - noop
  - left
  - up
  - right
  - down
  allowFrameRateChange: false
  bucket: null
  dataFile: episode
  frameRateStepSize: 5
  game: GDY-Labyrinth-v0
  maxEpisodes: 20
  maxFrameRate: 60
  minFrameRate: 1
  projectId: null
  s3upload: true
  startingFrameRate: 30
  ui:
  - left
  - up
  - right
  - down
  - start
  - stop
  - pause
  - reset
  - good
  - bad
  - demonstrate
