trial:
  actionBufferLifespan: 1
  actionSpace:
  - NOOP
  - FIRE
  - RIGHT
  - LEFT
  - RIGHTFIRE
  - LEFTFIRE
  allowFrameRateChange: false
  bucket: null
  dataFile: episode
  frameRateStepSize: 5
  game: PongNoFrameskip-v4
  maxEpisodes: 2
  maxFrameRate: 60
  minFrameRate: 1
  projectId: null
  s3upload: true
  startingFrameRate: 30
  ui:
  - start
  - stop
  - pause
  - reset
  - good
  - reallygood
  - bad
